# ~~~~~~~~~~~~~~~~~~~~~~basic~~~~~~~~~~~~~~~~~~~~~#
spring.application.name: spring-boot-api-sd

spring:
  profiles:
    active: dev
  # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  # 数据源
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}

# ~~~~~~~~~~~~所有环境通用的配置，放在这里~~~~~~~~~~~~~#
swagger:
  version: @project.version@
  api-docs:
    enable: ${swagger.enable:true}
    title: api
    description: api服务列表

