# ~~~~~~~~~~~~~~~~~~~~~~basic~~~~~~~~~~~~~~~~~~~~~#
spring:
  profiles:
    active: dev
  # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  # 数据源
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}

# ~~~~~~~~~~~~所有环境通用的配置，放在这里~~~~~~~~~~~~~#

#swagger配置参考https://github.com/SpringForAll/spring-boot-starter-swagger
swagger:
  # 是否启用swagger，默认：true
  enabled: true
  # 标题
  title: "API"
  contact:
    # 维护人
    name: "zhout"
    email: "tbuddha@qq.com"
    url: "https://github.com/TBuddha/spring-boot-api-sd"
  # 版本
  version: @project.version@
  # 描述
  description: "API 描述"
  # swagger扫描的基础包，默认：全扫描
  base-package: "com.company.project.web"
  # 需要处理的基础URL规则，默认：/**
  base-path: /**
  # 需要排除的URL规则，默认：空
  exclude-path: /error, /ops/**
  license: "Apache License, Version 2.0"
  license-url: "https://www.apache.org/licenses/LICENSE-2.0.html"
